apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: pcg-redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: pcg-redis
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: pcg-redis
spec:
  restartPolicy: Never
  containers:
    - name: redis
      image: redis:5.0.4-alpine
      imagePullPolicy: Always
      resources:
        requests:
          memory: 15Gi      
      command: ["redis-server"]
      args: ["--requirepass", "dev"]
      ports:
        - containerPort: 6379
  nodeSelector:
    nodetype: redis-server