apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.masterDeployment.name | quote }}
  labels:
    app: {{ .Values.masterDeployment.name | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.masterDeployment.name | quote }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.masterDeployment.name | quote }}
    spec:
      {{- template "chunkedgraph-ingest.volumes" . }}
      dnsPolicy: Default
      containers:
        - name: {{ .Values.masterDeployment.name | quote }}
          image: "{{ .Values.masterDeployment.image.repository }}:{{ .Values.masterDeployment.image.tag }}"
          imagePullPolicy: {{ .Values.masterDeployment.image.pullPolicy | quote }}
          resources:
            {{- toYaml .Values.masterDeployment.resources | nindent 12 }}
          envFrom:
          {{- range .Values.env }}
          - configMapRef:
              name: {{ .name }}
          {{- end }}
          {{- template "chunkedgraph-ingest.volume-mounts" . }}
          command: [bash, -c, "trap : TERM INT; sleep infinity & wait"]
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.masterDeployment.name | quote }}