steps:
  # Login to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker login --username=$$USERNAME --password=$$PASSWORD"]
    secretEnv: ["USERNAME", "PASSWORD"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build -t $$USERNAME/pychunkedgraph:$TAG_NAME .
    timeout: 600s
    secretEnv: ["USERNAME"]

  # Push the final image to Dockerhub
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker push $$USERNAME/pychunkedgraph:$TAG_NAME"]
    secretEnv: ["USERNAME"]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/1
      env: "PASSWORD"
    - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/1
      env: "USERNAME"
