steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/pychunkedgraph', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build -t gcr.io/$PROJECT_ID/pychunkedgraph:$TAG_NAME .
  timeout: 1500s
#- name: 'gcr.io/cloud-builders/docker'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    [[ "$BRANCH_NAME" == "master" ]] && docker build -t gcr.io/$PROJECT_ID/pychunkedgraph .
images:
- 'gcr.io/$PROJECT_ID/pychunkedgraph:$TAG_NAME'
