version: '3'
services:
  web:
    build: .
    restart: always
    ports:
     - "4000:4000"
    volumes:
     - .:/code
     - ~/.cloudvolume/secrets/google-secret.json:/root/.cloudvolume/secrets/google-secret.json
  redis:
    image: "redis:alpine"