name: pychunkedgraph
channels:
  - conda-forge
dependencies:
  - python==3.12.8
  - pip
  - tox
  - numpy
  - uwsgi
  - graph-tool-base==2.98
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt