# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chunkEdges.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chunkEdges.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x63hunkEdges.proto\x12\x04test\"<\n\x05\x45\x64ges\x12\x10\n\x08\x65\x64geList\x18\x01 \x01(\x0c\x12\x12\n\naffinities\x18\x02 \x01(\x0c\x12\r\n\x05\x61reas\x18\x03 \x01(\x0c\x62\x06proto3')
)




_EDGES = _descriptor.Descriptor(
  name='Edges',
  full_name='test.Edges',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edgeList', full_name='test.Edges.edgeList', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='affinities', full_name='test.Edges.affinities', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='areas', full_name='test.Edges.areas', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Edges'] = _EDGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Edges = _reflection.GeneratedProtocolMessageType('Edges', (_message.Message,), {
  'DESCRIPTOR' : _EDGES,
  '__module__' : 'chunkEdges_pb2'
  # @@protoc_insertion_point(class_scope:test.Edges)
  })
_sym_db.RegisterMessage(Edges)


# @@protoc_insertion_point(module_scope)
