# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chunkComponents.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chunkComponents.proto',
  package='components',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x63hunkComponents.proto\x12\ncomponents\"(\n\x12\x43hunkComponentsMsg\x12\x12\n\ncomponents\x18\x01 \x03(\x04\x62\x06proto3')
)




_CHUNKCOMPONENTSMSG = _descriptor.Descriptor(
  name='ChunkComponentsMsg',
  full_name='components.ChunkComponentsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='components', full_name='components.ChunkComponentsMsg.components', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['ChunkComponentsMsg'] = _CHUNKCOMPONENTSMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChunkComponentsMsg = _reflection.GeneratedProtocolMessageType('ChunkComponentsMsg', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKCOMPONENTSMSG,
  '__module__' : 'chunkComponents_pb2'
  # @@protoc_insertion_point(class_scope:components.ChunkComponentsMsg)
  })
_sym_db.RegisterMessage(ChunkComponentsMsg)


# @@protoc_insertion_point(module_scope)
