# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chunkEdges.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chunkEdges.proto',
  package='edges',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x63hunkEdges.proto\x12\x05\x65\x64ges\"S\n\x08\x45\x64gesMsg\x12\x11\n\tnode_ids1\x18\x01 \x01(\x0c\x12\x11\n\tnode_ids2\x18\x02 \x01(\x0c\x12\x12\n\naffinities\x18\x03 \x01(\x0c\x12\r\n\x05\x61reas\x18\x04 \x01(\x0c\"\x80\x01\n\rChunkEdgesMsg\x12!\n\x08in_chunk\x18\x01 \x01(\x0b\x32\x0f.edges.EdgesMsg\x12$\n\x0b\x63ross_chunk\x18\x02 \x01(\x0b\x32\x0f.edges.EdgesMsg\x12&\n\rbetween_chunk\x18\x03 \x01(\x0b\x32\x0f.edges.EdgesMsgb\x06proto3')
)




_EDGESMSG = _descriptor.Descriptor(
  name='EdgesMsg',
  full_name='edges.EdgesMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_ids1', full_name='edges.EdgesMsg.node_ids1', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_ids2', full_name='edges.EdgesMsg.node_ids2', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='affinities', full_name='edges.EdgesMsg.affinities', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='areas', full_name='edges.EdgesMsg.areas', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=110,
)


_CHUNKEDGESMSG = _descriptor.Descriptor(
  name='ChunkEdgesMsg',
  full_name='edges.ChunkEdgesMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='in_chunk', full_name='edges.ChunkEdgesMsg.in_chunk', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cross_chunk', full_name='edges.ChunkEdgesMsg.cross_chunk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='between_chunk', full_name='edges.ChunkEdgesMsg.between_chunk', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=241,
)

_CHUNKEDGESMSG.fields_by_name['in_chunk'].message_type = _EDGESMSG
_CHUNKEDGESMSG.fields_by_name['cross_chunk'].message_type = _EDGESMSG
_CHUNKEDGESMSG.fields_by_name['between_chunk'].message_type = _EDGESMSG
DESCRIPTOR.message_types_by_name['EdgesMsg'] = _EDGESMSG
DESCRIPTOR.message_types_by_name['ChunkEdgesMsg'] = _CHUNKEDGESMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EdgesMsg = _reflection.GeneratedProtocolMessageType('EdgesMsg', (_message.Message,), {
  'DESCRIPTOR' : _EDGESMSG,
  '__module__' : 'chunkEdges_pb2'
  # @@protoc_insertion_point(class_scope:edges.EdgesMsg)
  })
_sym_db.RegisterMessage(EdgesMsg)

ChunkEdgesMsg = _reflection.GeneratedProtocolMessageType('ChunkEdgesMsg', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKEDGESMSG,
  '__module__' : 'chunkEdges_pb2'
  # @@protoc_insertion_point(class_scope:edges.ChunkEdgesMsg)
  })
_sym_db.RegisterMessage(ChunkEdgesMsg)


# @@protoc_insertion_point(module_scope)
