# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chunkMapping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chunkMapping.proto',
  package='mapping',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63hunkMapping.proto\x12\x07mapping\":\n\x0f\x43hunkMappingMsg\x12\x13\n\x0bsupervoxels\x18\x01 \x01(\x0c\x12\x12\n\ncomponents\x18\x02 \x01(\x0c\x62\x06proto3')
)




_CHUNKMAPPINGMSG = _descriptor.Descriptor(
  name='ChunkMappingMsg',
  full_name='mapping.ChunkMappingMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='supervoxels', full_name='mapping.ChunkMappingMsg.supervoxels', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='components', full_name='mapping.ChunkMappingMsg.components', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['ChunkMappingMsg'] = _CHUNKMAPPINGMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChunkMappingMsg = _reflection.GeneratedProtocolMessageType('ChunkMappingMsg', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKMAPPINGMSG,
  '__module__' : 'chunkMapping_pb2'
  # @@protoc_insertion_point(class_scope:mapping.ChunkMappingMsg)
  })
_sym_db.RegisterMessage(ChunkMappingMsg)


# @@protoc_insertion_point(module_scope)
