apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      dnsPolicy: Default           
      containers:
        - name: redis
          image: redis:5-alpine
          imagePullPolicy: Always
          resources:
            requests:
              memory: 12G
          command: ["redis-server"] # redis-server --requirepass dev --save "" --appendonly "no"
          args: ["--requirepass", "dev", "--save", "", "--appendonly", "no"]
          ports:
            - containerPort: 6379
      nodeSelector:
        cloud.google.com/gke-nodepool: redis