apiVersion: v1
kind: Service
metadata:
  name: pcg
  labels:
    app: master
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    name: pcg
  - port: 8888
    targetPort: 8888
    name: jupyter
  selector:
    app: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: master
spec:
  selector:
    matchLabels:
      app: master
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      dnsPolicy: Default
      volumes:
        - name: google-secret
          secret:
            secretName: google-secret
        - name: chunkedgraph-secret
          secret:
            secretName: chunkedgraph-secret            
        - name: microns-seunglab-google-secret
          secret:
            secretName: microns-seunglab-google-secret
        - name: seunglab2-google-secret
          secret:
            secretName: seunglab2-google-secret
        # - name: ranl-scratch-google-secret
        #   secret:
        #     secretName: ranl-scratch-google-secret
        # - name: jupyter-notebook-config
        #   secret:
        #     secretName: jupyter-notebook-config
      containers:
        - name: master
          image: gcr.io/neuromancer-seung-import/pychunkedgraph:manuel-minnie-mesh2
          imagePullPolicy: Always
          resources:
            requests:
              memory: 5G
          env:
            - name: APP_SETTINGS
              value: pychunkedgraph.app.config.DeploymentWithRedisConfig
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.cloudvolume/secrets/google-secret.json
            - name: FLASK_APP
              value: run_dev.py
            - name: REDIS_PASSWORD
              value: dev # for development
            - name: SHELL
              value: /bin/bash
          volumeMounts:
            - name: google-secret
              mountPath: /root/.cloudvolume/secrets/google-secret.json
              subPath: google-secret.json
              readOnly: true
            - name: chunkedgraph-secret
              mountPath: /root/.cloudvolume/secrets/chunkedgraph-secret.json
              subPath: chunkedgraph-secret.json
              readOnly: true              
            - name: microns-seunglab-google-secret
              mountPath: /root/.cloudvolume/secrets/microns-seunglab-google-secret.json
              subPath: microns-seunglab-google-secret.json
              readOnly: true                
            - name: seunglab2-google-secret
              mountPath: /root/.cloudvolume/secrets/seunglab2-google-secret.json
              subPath: seunglab2-google-secret.json
              readOnly: true
            # - name: ranl-scratch-google-secret
            #   mountPath: /root/.cloudvolume/secrets/ranl-scratch-google-secret.json
            #   subPath: ranl-scratch-google-secret.json
            #   readOnly: true
            # - name: jupyter-notebook-config
            #   mountPath: /root/.jupyter/jupyter_notebook_config.json
            #   subPath: jupyter_notebook_config.json
            #   readOnly: true              
          # command: [bash, -c, "python run_dev.py 4000"]
          command: [bash, -c, "trap : TERM INT; sleep infinity & wait"]
      nodeSelector:
        cloud.google.com/gke-nodepool: master
