apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomic-worker
  labels:
    app: atomic-worker
spec:
  selector:
    matchLabels:
      app: atomic-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: atomic-worker
    spec:
      dnsPolicy: Default
      volumes:
        - name: google-secret
          secret:
            secretName: google-secret
        - name: chunkedgraph-google-secret
          secret:
            secretName: chunkedgraph-google-secret             
        - name: microns-seunglab-google-secret
          secret:
            secretName: microns-seunglab-google-secret
        # - name: seunglab2-google-secret
        #   secret:
        #     secretName: seunglab2-google-secret
        # - name: ranl-scratch-google-secret
        #   secret:
        #     secretName: ranl-scratch-google-secret
      containers:
        - name: atomic-worker
          image: gcr.io/neuromancer-seung-import/pychunkedgraph:manuel-mesh
          imagePullPolicy: Always
          resources:
            requests:
              memory: 3.5G
          env:
            - name: APP_SETTINGS
              value: pychunkedgraph.app.config.DeploymentWithRedisConfig
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.cloudvolume/secrets/google-secret.json              
            - name: FLASK_APP
              value: run_dev.py
            - name: REDIS_PASSWORD
              value: dev # for development
          volumeMounts:
            - name: google-secret
              mountPath: /root/.cloudvolume/secrets/google-secret.json
              subPath: google-secret.json
              readOnly: true
            - name: chunkedgraph-google-secret
              mountPath: /root/.cloudvolume/secrets/chunkedgraph-google-secret.json
              subPath: chunkedgraph-google-secret.json
              readOnly: true
            - name: microns-seunglab-google-secret
              mountPath: /root/.cloudvolume/secrets/microns-seunglab-google-secret.json
              subPath: microns-seunglab-google-secret.json
              readOnly: true                
            # - name: seunglab2-google-secret
            #   mountPath: /root/.cloudvolume/secrets/seunglab2-google-secret.json
            #   subPath: seunglab2-google-secret.json
            #   readOnly: true
            # - name: ranl-scratch-google-secret
            #   mountPath: /root/.cloudvolume/secrets/ranl-scratch-google-secret.json
            #   subPath: ranl-scratch-google-secret.json
            #   readOnly: true              
          command: ["rq"]
          args: ["worker", "-c", "rq_workers.mesh_worker"]
          # command: [bash, -c, "trap : TERM INT; sleep infinity & wait"]
      nodeSelector:
        cloud.google.com/gke-nodepool: worker