apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomic-worker
  labels:
    app: atomic-worker
spec:
  selector:
    matchLabels:
      app: atomic-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: atomic-worker
    spec:
      dnsPolicy: Default
      volumes:
        - name: google-secret
          secret:
            secretName: google-secret
        - name: chunkedgraph-secret
          secret:
            secretName: chunkedgraph-secret             
        - name: microns-seunglab-google-secret
          secret:
            secretName: microns-seunglab-google-secret
        - name: seunglab2-google-secret
          secret:
            secretName: seunglab2-google-secret
        - name: aws-secret
          secret:
            secretName: aws-secret
        # - name: ranl-scratch-google-secret
        #   secret:
        #     secretName: ranl-scratch-google-secret
      containers:
        - name: atomic-worker
          image: gcr.io/neuromancer-seung-import/pychunkedgraph:manuel-minnie-mesh
          imagePullPolicy: Always
          resources:
            requests:
              memory: 25G
          env:
            - name: APP_SETTINGS
              value: pychunkedgraph.app.config.DeploymentWithRedisConfig
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.cloudvolume/secrets/google-secret.json              
            - name: FLASK_APP
              value: run_dev.py
            - name: REDIS_PASSWORD
              value: dev # for development
          volumeMounts:
            - name: google-secret
              mountPath: /root/.cloudvolume/secrets/google-secret.json
              subPath: google-secret.json
              readOnly: true
            - name: chunkedgraph-secret
              mountPath: /root/.cloudvolume/secrets/chunkedgraph-secret.json
              subPath: chunkedgraph-secret.json
              readOnly: true
            - name: microns-seunglab-google-secret
              mountPath: /root/.cloudvolume/secrets/microns-seunglab-google-secret.json
              subPath: microns-seunglab-google-secret.json
              readOnly: true                
            - name: seunglab2-google-secret
              mountPath: /root/.cloudvolume/secrets/seunglab2-google-secret.json
              subPath: seunglab2-google-secret.json
              readOnly: true
            - name: aws-secret
              mountPath: /root/.cloudvolume/secrets/aws-secret.json
              subPath: aws-secret.json
              readOnly: true
            # - name: ranl-scratch-google-secret
            #   mountPath: /root/.cloudvolume/secrets/ranl-scratch-google-secret.
            #   subPath: ranl-scratch-google-secret.json
            #   readOnly: true              
          command: ["python"]
          args: ["pychunkedgraph/meshing/mesh_worker.py", "--queue_name", "manuel-seamless", "--lease_seconds", "43200"]
          # command: [bash, -c, "trap : TERM INT; sleep infinity & wait"]
      nodeSelector:
        cloud.google.com/gke-nodepool: worker