apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: atomic-hpa
  namespace: default
  labels:
    app: atomic-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atomic-worker
  minReplicas: 1
  maxReplicas: 3000
  targetCPUUtilizationPercentage: 75