"""
Extract sampled subgraph from real BigTable for offline e2e tests.
Produces test_data/e2e_fixture.pkl.

Algorithm:
1. Sample edges from wave files (read once, subsample per edge count)
2. Edge SVs → roots via parallel get_roots
3. BFS from roots top-down: read ALL nodes with ALL data (multiprocessing)
4. All L2s: keep ACX source SVs as children (all layers)
5. Filter ACX to edges with source SVs in kept children
6. Add ACX target SVs to their L2's children + parent rows

Run:
    from pychunkedgraph.debug.stitch_test.sample_test_data import extract
    extract(force=True)
"""

# pylint: disable=no-member
import gzip
import os
import pickle
import time
from pathlib import Path
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from multiprocessing import get_context

import numpy as np
from cloudvolume import CloudVolume
from cloudfiles import CloudFiles
from tqdm import tqdm
from google.cloud.bigtable.backup import Backup

os.environ.setdefault("BIGTABLE_PROJECT", "zetta-proofreading")
os.environ.setdefault("BIGTABLE_INSTANCE", "pychunkedgraph")

from pychunkedgraph.graph import ChunkedGraph, attributes, basetypes
from .tables import BACKUP_ID, CLUSTER_ID, EDGES_SRC, _get_instance

FIXTURE_DIR = Path(os.path.dirname(__file__)) / "fixtures"


def _fixture_path(n_edges: int) -> Path:
    return FIXTURE_DIR / f"e2e_fixture_{n_edges}e.pkl.gz"
SAMPLE_EDGES_PER_FILE = 2
RNG_SEED = 42
READ_BATCH = 1000
STATS_PATH = FIXTURE_DIR / "STATS.md"


def _update_stats(
    n_edges: int,
    node_store: dict,
    sampled_edges: dict,
    unique_roots: np.ndarray,
    all_sampled_svs: set,
    size_mb: float,
) -> None:
    """Update STATS.md with per-fixture statistics. Merges with existing entries."""
    from datetime import datetime

    layer_counts = defaultdict(int)
    n_acx = 0
    n_cx = 0
    for nid, data in node_store.items():
        layer = (nid >> 56) & 0xFF
        layer_counts[layer] += 1
        n_acx += sum(len(edges) for edges in data.get("acx", {}).values())
        n_cx += sum(len(edges) for edges in data.get("cx", {}).values())

    n_waves = len(sampled_edges)
    n_files = sum(len(v) for v in sampled_edges.values())
    total_edges = sum(len(e) for el in sampled_edges.values() for e in el)

    entry = (
        f"## {n_edges}e — `e2e_fixture_{n_edges}e.pkl.gz`\n"
        f"- **Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
        f"- **Size**: {size_mb:.1f} MB\n"
        f"- **Edges per file**: {n_edges}\n"
        f"- **Waves**: {n_waves}, files: {n_files}, total edges: {total_edges}\n"
        f"- **Edge SVs**: {len(all_sampled_svs)}\n"
        f"- **Roots**: {len(unique_roots)}\n"
        f"- **Node store**: {len(node_store)} nodes\n"
        f"- **Nodes per layer**: {dict(sorted(layer_counts.items()))}\n"
        f"- **ACX edges**: {n_acx}, **CX edges**: {n_cx}\n"
    )

    # Read existing, replace section for this n_edges, rewrite
    header = "# Fixture Stats\n\nAuto-generated by `sample_test_data.extract()`.\n\n"
    sections = {}
    if STATS_PATH.exists():
        content = STATS_PATH.read_text()
        for section in content.split("\n## ")[1:]:
            key = section.split("e — ")[0].strip()
            sections[key] = "## " + section.rstrip() + "\n"

    sections[str(n_edges)] = entry
    with open(STATS_PATH, "w") as f:
        f.write(header)
        for key in sorted(sections, key=int):
            f.write(sections[key] + "\n")


def _list_wave_files() -> dict:
    cf = CloudFiles(EDGES_SRC)
    all_files = sorted(f for f in cf.list() if f.startswith("task_") and f.endswith(".edges"))
    waves = defaultdict(list)
    for f in all_files:
        waves[int(f.split("_")[1])].append(f)
    return dict(sorted(waves.items()))


def _sample_edges(args: tuple) -> np.ndarray:
    cf_url, filename, n, seed = args
    cf = CloudFiles(cf_url)
    edges = pickle.loads(cf.get(filename))
    if len(edges) <= n:
        return edges
    rng = np.random.default_rng(seed)
    return edges[rng.choice(len(edges), size=n, replace=False)]


def _get_roots_worker(args: tuple) -> np.ndarray:
    table_name, sv_list = args
    cg = ChunkedGraph(graph_id=table_name)
    sv_arr = np.array(sv_list, dtype=basetypes.NODE_ID)
    return cg.get_roots(sv_arr)


def _read_node_batch_worker(args: tuple) -> dict:
    """Worker: create CG client, read batch of nodes."""
    table_name, node_ids_list = args
    cg = ChunkedGraph(graph_id=table_name)
    node_ids = np.array(node_ids_list, dtype=basetypes.NODE_ID)
    lc = cg.meta.layer_count
    props = (
        [attributes.Hierarchy.Parent, attributes.Hierarchy.Child]
        + [attributes.Connectivity.AtomicCrossChunkEdge[l] for l in range(2, lc)]
        + [attributes.Connectivity.CrossChunkEdge[l] for l in range(2, lc)]
    )
    raw = cg.client.read_nodes(node_ids=node_ids, properties=props)
    result = {}
    for nid in node_ids:
        data = raw.get(nid, {})
        node = {}
        p = data.get(attributes.Hierarchy.Parent, [])
        if p:
            node["parent"] = int(p[0].value)
        ch = data.get(attributes.Hierarchy.Child, [])
        if ch:
            node["children"] = ch[0].value.copy()
        acx = {}
        for layer in range(2, lc):
            cells = data.get(attributes.Connectivity.AtomicCrossChunkEdge[layer], [])
            if cells and len(cells[0].value) > 0:
                acx[layer] = cells[0].value.copy()
        if acx:
            node["acx"] = acx
        cx = {}
        for layer in range(2, lc):
            cells = data.get(attributes.Connectivity.CrossChunkEdge[layer], [])
            if cells and len(cells[0].value) > 0:
                cx[layer] = cells[0].value.copy()
        if cx:
            node["cx"] = cx
        result[int(nid)] = node
    return result


def _bfs_from_roots(cg: ChunkedGraph, root_ids: np.ndarray) -> dict:
    """BFS top-down from roots. Read ALL nodes at each level in parallel batches."""
    store = {}
    current = root_ids.copy()
    level = 0
    t0 = time.time()
    table_name = cg.meta.graph_config.ID
    n_workers = max(os.cpu_count(), 16)

    while len(current) > 0:
        level += 1
        batches = [
            current[i:i + READ_BATCH].tolist()
            for i in range(0, len(current), READ_BATCH)
        ]
        args = [(table_name, b) for b in batches]
        with get_context("fork").Pool(min(n_workers, len(args))) as pool:
            for batch_data in tqdm(pool.imap_unordered(_read_node_batch_worker, args), total=len(args), desc=f"  level {level}"):
                store.update(batch_data)
        elapsed = time.time() - t0
        layers = cg.get_chunk_layers(current)
        layer_counts = dict(zip(*np.unique(layers, return_counts=True)))
        print(f"  level {level}: {len(current)} nodes {layer_counts} ({elapsed:.1f}s)", flush=True)

        next_level = []
        for nid in current:
            data = store.get(int(nid), {})
            children = data.get("children")
            if children is not None:
                layer = (int(nid) >> 56) & 0xFF
                if layer > 2:
                    next_level.extend(int(c) for c in children if int(c) not in store)

        if not next_level:
            break
        current = np.array(list(set(next_level)), dtype=basetypes.NODE_ID)

    print(f"  BFS complete: {len(store)} nodes in {time.time() - t0:.1f}s")
    return store


def _build_fixture_store(real_data: dict, edge_svs: set) -> dict:
    """Build self-consistent fixture from complete BFS data.

    - L3+ nodes: copied as-is
    - L2 nodes: children = ACX source SVs (all layers) + edge SVs, CX preserved, ACX filtered
    - SVs: parent row for every SV in the graph (including ACX targets and edge SVs)
    """
    rng = np.random.default_rng(99)
    store = {}
    real_sv_to_l2 = {}
    all_kept_svs = set()
    l2_nodes = {}

    # Single pass: separate L2 from L3+, build SV→L2 map
    for nid, data in real_data.items():
        layer = (nid >> 56) & 0xFF
        if layer > 2:
            store[nid] = dict(data)
        elif layer == 2:
            l2_nodes[nid] = data
            for sv in data.get("children", []):
                real_sv_to_l2[int(sv)] = nid

    # L2 nodes: keep ACX source SVs + edge SVs that belong to this L2, filter ACX, preserve CX
    for nid, data in l2_nodes.items():
        real_children = data.get("children")
        if real_children is None or len(real_children) == 0:
            store[nid] = {k: v for k, v in data.items() if k != "children"}
            continue

        real_ch_set = set(int(sv) for sv in real_children)
        keep_svs = {
            int(e[0]) for edges in data.get("acx", {}).values()
            for e in edges if int(e[0]) in real_ch_set
        }
        # Edge SVs that belong to this L2 must be kept
        keep_svs |= real_ch_set & edge_svs
        # Fallback: at least 1 random SV if nothing else
        if not keep_svs:
            keep_svs = {int(real_children[rng.choice(len(real_children))])}

        all_kept_svs.update(keep_svs)
        my_svs = np.array(sorted(keep_svs), dtype=basetypes.NODE_ID)

        node = {"children": my_svs}
        if "parent" in data:
            node["parent"] = data["parent"]
        if "cx" in data:
            node["cx"] = data["cx"]
        if "acx" in data:
            filtered_acx = {
                lyr: edges[mask]
                for lyr, edges in data["acx"].items()
                if (mask := np.array([int(e[0]) in keep_svs for e in edges])).any()
            }
            if filtered_acx:
                node["acx"] = filtered_acx
        store[nid] = node

    # ACX target SVs: batch per L2, update children once
    acx_target_svs = {
        int(e[1]) for data in store.values() if "acx" in data
        for edges in data["acx"].values() for e in edges
    }
    l2_additions = defaultdict(set)
    for tgt_sv in acx_target_svs:
        l2 = real_sv_to_l2.get(tgt_sv)
        if l2 is not None and l2 in store:
            all_kept_svs.add(tgt_sv)
            l2_additions[l2].add(tgt_sv)
    for l2, new_svs in l2_additions.items():
        existing = set(int(s) for s in store[l2].get("children", []))
        combined = existing | new_svs
        if len(combined) > len(existing):
            store[l2]["children"] = np.array(sorted(combined), dtype=basetypes.NODE_ID)

    # SV parent rows
    for sv_int in all_kept_svs:
        if sv_int not in store:
            l2 = real_sv_to_l2.get(sv_int)
            if l2 is not None:
                store[sv_int] = {"parent": l2}

    return store


def extract(
    edges_range: tuple = (1, 4),
    seed: int = RNG_SEED,
    force: bool = False,
) -> list:
    """Extract fixtures for each edge count in range. Restores table once."""
    start, end = edges_range
    counts = list(range(start, end))

    # Check which need extraction
    to_extract = []
    for n in counts:
        path = _fixture_path(n)
        if os.path.exists(path) and not force:
            print(f"Fixture exists: {path} ({os.path.getsize(path) / 1e6:.1f} MB)")
        else:
            to_extract.append(n)

    if not to_extract:
        return [_fixture_path(n) for n in counts]

    # Restore table once
    table_name = "stitch_redesign_test_e2e_sample"
    instance = _get_instance()
    tab = instance.table(table_name)
    if not tab.exists():
        Backup(BACKUP_ID, instance, cluster_id=CLUSTER_ID).restore(table_name).result()
        print(f"Restored {table_name}")
    else:
        print(f"Reusing {table_name}")

    wave_files = _list_wave_files()
    n_files = sum(len(v) for v in wave_files.values())
    print(f"Waves: {list(wave_files.keys())}, files: {n_files}")
    max_n = max(to_extract)

    try:
        cg = ChunkedGraph(graph_id=table_name)
        meta_bytes = pickle.dumps(cg.meta)
        cv_info = CloudVolume(cg.meta.data_source.WATERSHED, mip=0).info

        # Read all edge files once with max edge count, subsample per n
        rng = np.random.default_rng(seed)
        file_seeds = rng.integers(0, 2**31, size=n_files)
        all_wave_args = []
        idx = 0
        for wave, files in wave_files.items():
            for f in files:
                all_wave_args.append((EDGES_SRC, f, max_n, int(file_seeds[idx])))
                idx += 1
        print(f"Reading {n_files} edge files (max {max_n} edges each)...")
        with ThreadPoolExecutor(max_workers=16) as pool:
            all_file_edges = list(pool.map(_sample_edges, all_wave_args))

        for n in to_extract:
            print(f"\n--- Extracting {n} edges per file ---")
            # Subsample from cached reads
            sub_rng = np.random.default_rng(seed)
            sampled_edges = {}
            all_sampled_svs = set()
            idx = 0
            for wave, files in wave_files.items():
                wave_results = []
                for _ in files:
                    edges = all_file_edges[idx]
                    if len(edges) > n:
                        sel = sub_rng.choice(len(edges), size=n, replace=False)
                        edges = edges[sel]
                    else:
                        sub_rng.choice(1)  # advance rng state
                    wave_results.append(edges)
                    all_sampled_svs.update(edges.ravel().tolist())
                    idx += 1
                sampled_edges[wave] = wave_results
            print(f"Sampled {len(all_sampled_svs)} unique SVs")

            if not all_sampled_svs:
                print("No SVs sampled, skipping")
                continue

            # Parallel get_roots
            sv_arr = np.array(list(all_sampled_svs), dtype=basetypes.NODE_ID)
            n_workers = max(os.cpu_count(), 16)
            roots_batch = max(1, len(sv_arr) // n_workers)
            batches = [sv_arr[i:i + roots_batch].tolist() for i in range(0, len(sv_arr), roots_batch)]
            args = [(table_name, b) for b in batches]
            all_roots = []
            with get_context("fork").Pool(min(n_workers, len(args))) as pool:
                for batch_roots in tqdm(pool.imap_unordered(_get_roots_worker, args), total=len(args), desc="  get_roots"):
                    all_roots.append(batch_roots)
            roots = np.concatenate(all_roots) if all_roots else np.array([], dtype=basetypes.NODE_ID)
            unique_roots = np.unique(roots)
            print(f"Edge SVs: {len(sv_arr)}, roots: {len(unique_roots)}")

            print("BFS from roots...")
            real_data = _bfs_from_roots(cg, unique_roots)

            node_store = _build_fixture_store(real_data, edge_svs=all_sampled_svs)
            print(f"Fixture store: {len(node_store)} nodes")

            fixture_path = _fixture_path(n)
            fixture = {
                "edges_per_wave": {w: [e.tolist() for e in el] for w, el in sampled_edges.items()},
                "node_store": node_store,
                "meta_bytes": meta_bytes,
                "cv_info": cv_info,
                "sample_config": {"edges_per_file": n, "seed": seed},
            }
            with gzip.open(fixture_path, "wb") as f:
                pickle.dump(fixture, f)
            size_mb = os.path.getsize(fixture_path) / 1e6
            print(f"Fixture saved: {fixture_path} ({size_mb:.1f} MB)")
            _update_stats(n, node_store, sampled_edges, unique_roots, all_sampled_svs, size_mb)

    finally:
        instance.table(table_name).delete()
        print(f"Deleted {table_name}")

    return [_fixture_path(n) for n in counts]
