"""
End-to-end multiwave stitch test using sampled real data + BigTable emulator.

Fixture: test_data/e2e_fixture.pkl (generated by sample_test_data.py)
Emulator: gcloud beta emulators bigtable start

Runs production add_edges and our stitch on identical emulator tables,
compares components (SV sets) at every layer after each wave.
"""

import atexit
import os
import pickle
import signal
import socket
import subprocess
import time
from collections import defaultdict
from datetime import timedelta
from pathlib import Path

import numpy as np
import pytest
from google.auth import credentials
from google.cloud import bigtable

from cloudvolume import CloudVolume

from pychunkedgraph.graph import ChunkedGraph, attributes, basetypes, serializers
from pychunkedgraph.ingest.utils import bootstrap

import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from multiprocessing import Pool

multiprocessing.set_start_method("spawn", force=True)

from . import local_cg as _lcg_mod
from . import stitch as _stitch_mod
from .debug_single import _get_components, _print_component_comparison

N_WORKERS = 2
_shared_cache = None
_shared_inc = None

FIXTURE_PATH = Path(__file__).parent / "test_data" / "e2e_fixture.pkl"
EMULATOR_PORT = 8540  # different from pcg tests to avoid conflict

_emulator_proc = None
_emulator_cleaned = False


def _cleanup_emulator():
    global _emulator_cleaned
    if _emulator_cleaned or _emulator_proc is None:
        return
    _emulator_cleaned = True
    try:
        pgid = os.getpgid(_emulator_proc.pid)
        os.killpg(pgid, signal.SIGTERM)
        try:
            _emulator_proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            os.killpg(pgid, signal.SIGKILL)
            _emulator_proc.wait(timeout=5)
    except (ProcessLookupError, OSError, ChildProcessError):
        pass
    subprocess.run(["pkill", "-9", "cbtemulator"], stderr=subprocess.DEVNULL)


EMU_PROJECT = "test_project"
EMU_INSTANCE = "test_instance"


def _wait_port_free(port: int, timeout: int = 10) -> None:
    for _ in range(timeout * 10):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            if s.connect_ex(("localhost", port)) != 0:
                return
        time.sleep(0.1)
    raise RuntimeError(f"Port {port} not free after {timeout}s")


def _start_emulator():
    global _emulator_proc, _emulator_cleaned
    _emulator_cleaned = False
    subprocess.run(["pkill", "-9", "cbtemulator"], stderr=subprocess.DEVNULL)
    _wait_port_free(EMULATOR_PORT)
    _emulator_proc = subprocess.Popen(
        ["gcloud", "beta", "emulators", "bigtable", "start",
         f"--host-port=localhost:{EMULATOR_PORT}"],
        preexec_fn=os.setsid,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    atexit.register(_cleanup_emulator)
    os.environ["BIGTABLE_EMULATOR_HOST"] = f"localhost:{EMULATOR_PORT}"
    os.environ["BIGTABLE_PROJECT"] = EMU_PROJECT
    os.environ["BIGTABLE_INSTANCE"] = EMU_INSTANCE

    for _ in range(10):
        try:
            c = bigtable.Client(
                project=EMU_PROJECT,
                credentials=credentials.AnonymousCredentials(),
                admin=True,
            )
            t = c.instance(EMU_INSTANCE).table("_probe")
            t.create()
            t.delete()
            return True
        except Exception:
            time.sleep(1)
    raise RuntimeError("BigTable emulator failed to start")


def _emu_config(graph_id: str, meta) -> dict:
    return {
        "data_source": {
            "EDGES": str(meta.data_source.EDGES),
            "COMPONENTS": str(meta.data_source.COMPONENTS),
            "WATERSHED": str(meta.data_source.WATERSHED),
        },
        "graph_config": {
            "CHUNK_SIZE": list(meta.graph_config.CHUNK_SIZE),
            "FANOUT": meta.graph_config.FANOUT,
            "SPATIAL_BITS": meta.graph_config.SPATIAL_BITS,
            "ID_PREFIX": meta.graph_config.ID_PREFIX,
            "ROOT_LOCK_EXPIRY": timedelta(seconds=5),
        },
        "backend_client": {
            "TYPE": "bigtable",
            "CONFIG": {
                "ADMIN": True,
                "READ_ONLY": False,
                "PROJECT": EMU_PROJECT,
                "INSTANCE": EMU_INSTANCE,
                "CREDENTIALS": credentials.AnonymousCredentials(),
                "MAX_ROW_KEY_COUNT": 16000,
            },
        },
        "ingest_config": {},
    }


def _create_graph_client(graph_id: str, meta) -> ChunkedGraph:
    """Connect to existing emulator table (no create)."""
    bt_meta, _, client_info = bootstrap(graph_id, config=_emu_config(graph_id, meta))
    cg = ChunkedGraph(graph_id=graph_id, meta=bt_meta, client_info=client_info)
    cg.meta.layer_count = meta.layer_count
    cg.meta.layer_chunk_bounds = meta.layer_chunk_bounds
    return cg


def _create_graph(graph_id: str, meta, cv_info: dict) -> ChunkedGraph:
    """Create a ChunkedGraph table against the emulator."""
    bt_meta, _, client_info = bootstrap(graph_id, config=_emu_config(graph_id, meta))
    cg = ChunkedGraph(graph_id=graph_id, meta=bt_meta, client_info=client_info)
    cg.create()
    cg.meta.layer_count = meta.layer_count
    cg.meta.layer_chunk_bounds = meta.layer_chunk_bounds
    cg.meta._ws_cv = CloudVolume(
        cg.meta.data_source.WATERSHED, info=cv_info, progress=False,
    )
    return cg


def _populate_table(graph_id: str, meta, node_store: dict) -> None:
    """Batch write all nodes from fixture into emulator table. Creates own CG client."""
    os.environ.setdefault("BIGTABLE_EMULATOR_HOST", f"localhost:{EMULATOR_PORT}")
    os.environ.setdefault("BIGTABLE_PROJECT", EMU_PROJECT)
    os.environ.setdefault("BIGTABLE_INSTANCE", EMU_INSTANCE)
    cg = _create_graph_client(graph_id, meta)
    BATCH = 16000
    entries = []
    total = len(node_store)
    written = 0
    t0 = time.time()
    for nid, data in node_store.items():
        val_dict = {}
        if "parent" in data and data["parent"] is not None:
            val_dict[attributes.Hierarchy.Parent] = np.uint64(data["parent"])
        if "children" in data and data["children"] is not None:
            val_dict[attributes.Hierarchy.Child] = np.asarray(data["children"], dtype=basetypes.NODE_ID)
        if "acx" in data:
            for layer, edges in data["acx"].items():
                val_dict[attributes.Connectivity.AtomicCrossChunkEdge[int(layer)]] = np.asarray(edges, dtype=basetypes.NODE_ID)
        if "cx" in data:
            for layer, edges in data["cx"].items():
                val_dict[attributes.Connectivity.CrossChunkEdge[int(layer)]] = np.asarray(edges, dtype=basetypes.NODE_ID)
        if val_dict:
            rk = serializers.serialize_uint64(np.uint64(nid))
            entries.append(cg.client.mutate_row(rk, val_dict))
        if len(entries) >= BATCH:
            cg.client.write(entries)
            written += len(entries)
            elapsed = time.time() - t0
            print(f"  {graph_id}: {written}/{total} ({written*100//total}%) {elapsed:.1f}s", flush=True)
            entries = []
    if entries:
        cg.client.write(entries)
        written += len(entries)

    # Set ID counters per chunk so batch_create_ids doesn't collide with existing nodes
    chunk_max = defaultdict(int)
    for nid in node_store:
        chunk_id = cg.get_chunk_id(np.uint64(nid))
        chunk_max[chunk_id] = max(chunk_max[chunk_id], nid)
    root_layer = cg.meta.layer_count
    for chunk_id, max_id in chunk_max.items():
        layer = cg.get_chunk_layer(np.uint64(chunk_id))
        if layer < root_layer:
            cg.id_client.set_max_node_id(chunk_id, max_id)

    print(f"  {graph_id}: {written}/{total} done in {time.time()-t0:.1f}s ({len(chunk_max)} chunks)", flush=True)


def _load_fixture() -> dict:
    assert FIXTURE_PATH.exists(), f"Fixture not found: {FIXTURE_PATH}. Run sample_test_data.extract() first."
    with open(FIXTURE_PATH, "rb") as f:
        return pickle.load(f)


def _e2e_worker(args):
    graph_id, edges_list, idx = args
    edges = np.array(edges_list, dtype=basetypes.NODE_ID)
    try:
        lcg = _lcg_mod.LocalChunkedGraph.create_worker(
            graph_id, preloaded=_shared_cache, incremental=_shared_inc,
        )
        lcg.begin_stitch()
        result = _stitch_mod.stitch(lcg, edges)
        lcg.mutate_rows(result.rows)
        snapshot = lcg.wave_snapshot()
        return [int(r) for r in result.new_roots], snapshot, None
    except Exception as e:
        import traceback
        return [], None, traceback.format_exc()


@pytest.fixture(scope="module")
def emulator():
    _start_emulator()
    yield
    _cleanup_emulator()


@pytest.fixture(scope="module")
def fixture():
    return _load_fixture()


class TestE2EMultiwave:
    """Full multiwave stitch: production vs ours on emulator, compared by SV components."""

    def test_all_waves(self, emulator, fixture):
        meta = pickle.loads(fixture["meta_bytes"])
        edges_per_wave = fixture["edges_per_wave"]
        node_store = fixture["node_store"]
        layer_count = meta.layer_count
        waves = sorted(int(w) for w in edges_per_wave.keys())

        # Create and populate two tables
        cv_info = fixture["cv_info"]
        cg_prod = _create_graph("e2e_prod", meta, cv_info)
        cg_ours = _create_graph("e2e_ours", meta, cv_info)
        print(f"Populating tables with {len(node_store)} nodes...")
        with ProcessPoolExecutor(max_workers=2) as ppe:
            f1 = ppe.submit(_populate_table, "e2e_prod", meta, node_store)
            f2 = ppe.submit(_populate_table, "e2e_ours", meta, node_store)
            f1.result(timeout=60)
            f2.result(timeout=60)

        # Set up our stitch lcg — inject the emulator CG directly
        lcg = _lcg_mod.LocalChunkedGraph.__new__(_lcg_mod.LocalChunkedGraph)
        lcg.cg = cg_ours
        lcg._cache = _lcg_mod.WaveCache()
        lcg.rpc_log = []
        lcg._read_row_keys = set()
        prod_all_roots = []
        ours_all_roots = []

        for wave in waves:
            wave_edges_list = edges_per_wave[wave]
            # Convert from lists back to arrays
            wave_edges = [np.array(e, dtype=basetypes.NODE_ID) for e in wave_edges_list if len(e) > 0]
            if not wave_edges:
                continue

            # Production: add_edges for each file (independent within wave)
            wave_prod_roots = []
            for edges in wave_edges:
                try:
                    result = cg_prod.add_edges("stitch", edges, stitch_mode=True)
                    wave_prod_roots.extend([int(r) for r in result.new_root_ids])
                except Exception as e:
                    import traceback
                    if not hasattr(self, '_prod_err_printed'):
                        traceback.print_exc()
                        self._prod_err_printed = True
            prod_all_roots.extend(wave_prod_roots)

            # Ours: stitch with Pool (2 workers)
            global _shared_cache, _shared_inc
            _shared_cache = lcg.preloaded()
            _shared_inc = lcg.incremental_state() if wave > 0 else None
            init_args = lcg.prepare_pool_init()

            args = [("e2e_ours", e.tolist(), i) for i, e in enumerate(wave_edges)]
            wave_ours_roots = []
            snapshots = []
            nw = min(N_WORKERS, len(args))
            with Pool(nw, initializer=_lcg_mod.LocalChunkedGraph.pool_init, initargs=init_args) as pool:
                for roots, snapshot, error in pool.imap_unordered(_e2e_worker, args):
                    if error:
                        pytest.fail(f"Stitch failed wave {wave}:\n{error}")
                    wave_ours_roots.extend(roots)
                    snapshots.append(snapshot)
            ours_all_roots.extend(wave_ours_roots)

            if snapshots:
                lcg.merge_wave_results(snapshots)

            print(f"wave {wave}: prod={len(wave_prod_roots)} ours={len(wave_ours_roots)} roots")

        # Final comparison
        print(f"\nTotal: prod={len(prod_all_roots)} ours={len(ours_all_roots)}")
        assert len(prod_all_roots) == len(ours_all_roots), \
            f"Root count mismatch: {len(prod_all_roots)} vs {len(ours_all_roots)}"

        # Component comparison at all layers
        prod_roots_arr = [np.uint64(r) for r in prod_all_roots]
        ours_roots_arr = [np.uint64(r) for r in ours_all_roots]

        comp_prod = _get_components(cg_prod, prod_roots_arr, layer_count)
        comp_ours = _get_components(
            ChunkedGraph(graph_id="e2e_ours", meta=meta),
            ours_roots_arr, layer_count,
        )
        _print_component_comparison(comp_prod, comp_ours, layer_count)

        for layer in range(2, layer_count + 1):
            p = comp_prod.get(layer, set())
            o = comp_ours.get(layer, set())
            assert p == o, f"Component mismatch at L{layer}: +prod={len(p-o)} +ours={len(o-p)}"

        # Cleanup
        cg_prod.client._admin_table.delete()
        cg_ours.client._admin_table.delete()
