# env configmaps from values file
{{- range .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  {{- range $key, $val := .vars }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
{{- end}}



# ingest config yaml file configmaps
{{- range $path, $_ :=  .Files.Glob  "config/*.yml" }}
{{- $fname := $path | base }}
{{- $name := $path | base | regexFind "^([^.]+)" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
data:
  {{ $fname }}: |-
  {{- range $.Files.Lines $path }}
    {{ . -}}
  {{ end }}
---
{{- end }}
