name: PyChunkedGraph

on:
  push:
    branches:
      - "main"
      - "pcgv1"
  pull_request:
    branches:
      - "main"
      - "pcgv1"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build image and run tests
        run: |
          docker build --tag seunglab/pychunkedgraph:$GITHUB_SHA .
          docker run --rm seunglab/pychunkedgraph:$GITHUB_SHA /bin/sh -c "pip install pytest>=7.0 && tox -v -- --cov-config .coveragerc --cov=pychunkedgraph && codecov"

