name: PyChunkedGraph

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build image and run tests
        run: |
          docker build --tag seunglab/pychunkedgraph:$TRAVIS_BRANCH . || travis_terminate 1
          docker run $ci_env --rm seunglab/pychunkedgraph:$TRAVIS_BRANCH /bin/sh -c "tox -v -- --cov-config .coveragerc --cov=pychunkedgraph && codecov"
    
