name: PyChunkedGraph

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build image and run tests
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          docker build --tag seunglab/pychunkedgraph:$GIT_HASH . || travis_terminate 1
          docker run $ci_env --rm seunglab/pychunkedgraph:$GIT_HASH /bin/sh -c "tox -v -- --cov-config .coveragerc --cov=pychunkedgraph && codecov"
    
